//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class OT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OT()
        {
            this.Operacion = new HashSet<Operacion>();
        }
    
        public int Id { get; set; }
        public int Numero { get; set; }
        public int IdMolde { get; set; }
        public Nullable<int> HorasTrabajo { get; set; }
        public string Tipo { get; set; }
        public string ClienteOT { get; set; }
        public bool Acabada { get; set; }
    
        public virtual Moldes Moldes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Operacion> Operacion { get; set; }
    }
}
