//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operacion
    {
        public int Id { get; set; }
        public string TipoOperacion { get; set; }
        public Nullable<int> Horas { get; set; }
        public int NumeroOT { get; set; }
        public Nullable<int> NuEmpleado { get; set; }
        public string EstadoOp { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual OT OT { get; set; }
    }
}
